version: '2'

services:
  manager:
    build: 
      context: ./manager
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
        NO_PROXY: $NO_PROXY
    container_name: hinemos-manager
    environment:
      LANG: ja_JP.UTF-8
      #LANG: en_US.UTF-8
    expose:
    - "8080"
    - "8081"
    ports:
    - "10080:80"
    - "161:161/udp"
    - "162:162/udp"
    - "514:514/udp"
    command:
    - /sbin/init
    # [WORK IN PROGRESS]
    # Please enable volume mount after below steps.
    # 1. `docker-compose up` with no volume mount.
    # 2. `mkdir -p /srv/docker/hinemos`
    # 3. `docker cp <CONTAINER ID of hinemos>:/opt/hinemos/var/data /srv/docker/hinemos/data`
    # 4. `chown 1000:1000 -R /srv/docker/hinemos/data`
    #
    #volumes:
    #- /srv/docker/hinemos/data:/opt/hinemos/var/data
